### ISSUE TITLE
Images don't seem to be loading?

### ISSUE THREAD

**Issue by alexford** [ptrkbrn/fully-loaded-nachos#1]
First of all, this is great. Totally in my cue zone.

For me, right now, searching works, but the images themselves seem to be timing out loading from backblaze.

---

I'd be interested in helping with this project if you'd like. I have a few other ideas for the front-end and would love to be able to get it running locally to try some things out. How did you generate the database/screenshots?

**Comment by ptrkbrn** [comment]
Seems to be working fine for me. What browser/device are you using?

**Comment by alexford** [comment]
Chrome and Safari on Mac. For example:

![image](https://user-images.githubusercontent.com/747580/125526674-85121796-9f11-4629-9532-e6ec3d57618d.png)

(I can't `curl` those image URLs either, they just time out)

Perhaps it's a network problem between me and the CDN.

**Comment by ptrkbrn** [comment]
Hmm. I'll check it out when I get home.

w/r/t  your second question, I'd be happy to have people contribute to the project. Let me know what you're thinking. I've got some general ideas of things but am completely open to suggestions.
My email is hi@ptrkbrn.com.
I generated the database using a Python script found here:
https://github.com/ptrkbrn/plain-pie

**Comment by ptrkbrn** [comment]
So I've tried this on a couple of device/browser combos and I've been unable to replicate the issue. I'm able to curl the URLs as well.
Any resolution on your end?

**Comment by alexford** [comment]
Okay, I tracked this down to a dumb setting on my home router — that's embarrassing!

I'll open other issues for ideas if that works for you

**Comment by ptrkbrn** [comment]
That works!
